### ISSUE TITLE
use DER serialized forms in public struct and function definitions

### ISSUE THREAD

**Issue by voisine** [netkicorp/c-partner-api-client#1]
Looking through the library API and it's looking nice.

One suggestion, in netki.h you include secp256k1.h and use secp256k1_pubkey and secp256k1_signature types in your function and struct definitions.

You can make the API ec library agnostic, and I think it's also recommended practice, if you use the DER serialized forms instead of the opaque libsecp structures. Then you can move the secp256k1.h include inside netki.c

**Comment by techguy613** [comment]
Hey @voisine! For some reason my mail client dropped this note into my Junk folder so I just saw this now. I'll shortly work on using DER serialized forms instead of the libsecp structures and make the header change. Thanks again for your feedback!

**Comment by techguy613** [comment]
Hey @voisine, I've updated the library with the changes you requested. Apologies for the lag, but I hope this finds you well! :)
